const API_URL = 'https://mr-phone-api.onrender.com';
const token = () => sessionStorage.getItem('mrPhoneAdminToken');
const money = n => 'TZS ' + Number(n).toLocaleString('en-TZ');
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
let products = JSON.parse(localStorage.mrProducts || '[]');
let reviews = JSON.parse(localStorage.mrReviews || '[]');
async function remote(path, options = {}) { const headers = {'Content-Type':'application/json', ...(options.headers || {})}; if (token()) headers.Authorization = `Bearer ${token()}`; const r = await fetch(API_URL + path, {...options, headers}); if (!r.ok) throw new Error(await r.text()); return r.status === 204 ? null : r.json(); }
function paint() { const list=document.querySelector('#adminList'), feedbackList=document.querySelector('#feedbackList'); if(list) list.innerHTML=products.map(p=>`<div class="admin-item"><div><b>${esc(p.name)}</b><small>${money(p.price)} · ${esc(p.brand)}</small></div><button class="delete" data-id="${esc(p.id)}">Delete</button></div>`).join('')||'<p class="muted">Hakuna bidhaa bado.</p>'; if(feedbackList) feedbackList.innerHTML=reviews.map((r,i)=>`<div class="admin-item"><div><b>${esc(r.name)}</b><small>${esc(r.city)} · ${esc(r.text)}</small></div><button class="delete" data-review="${i}">Delete</button></div>`).join('')||'<p class="muted">Hakuna feedback bado.</p>'; const count=document.querySelector('#feedbackCount'); if(count) count.textContent=reviews.length; document.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{try{await remote('/api/products',{method:'DELETE',body:JSON.stringify({id:b.dataset.id})})}catch(_){} products=products.filter(p=>p.id!==b.dataset.id);localStorage.mrProducts=JSON.stringify(products);paint()}); document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{reviews.splice(+b.dataset.review,1);localStorage.mrReviews=JSON.stringify(reviews);paint()}) }
window.loadRemoteAdmin = async () => { try{products=await remote('/api/products');localStorage.mrProducts=JSON.stringify(products)}catch(_){} try{reviews=await remote('/api/feedback');localStorage.mrReviews=JSON.stringify(reviews)}catch(_){} paint() };
document.querySelector('#productForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),p={id:'p'+Date.now(),name:f.get('name'),brand:f.get('brand'),meta:'Available now',price:Number(f.get('price')),image:f.get('image'),tag:'NEW'};try{await remote('/api/products',{method:'POST',body:JSON.stringify(p)});products.unshift(p);localStorage.mrProducts=JSON.stringify(products);e.target.reset();paint();alert('Bidhaa imeongezwa online.')}catch(_){alert('Imeshindikana kuhifadhi. Hakikisha ume-login na backend iko online.')}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#productsTab')?.classList.toggle('hidden',b.dataset.tab!=='products');document.querySelector('#feedbackTab')?.classList.toggle('hidden',b.dataset.tab!=='feedback')});
paint();
